spring:
  application:
    name: payment
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

flutterwave:
  secret-key: ${FLUTTERWAVE_SECRET_KEY}
  public-key: ${FLUTTERWAVE_PUBLIC_KEY}
  base-url: ${FLUTTERWAVE_BASE_URL}
